skku-comit/comit-website

app/(main)/_components/Footer.tsx
app/(main)/_components/Header.tsx
app/(main)/clubroom/page.tsx
app/(main)/layout.tsx
app/(main)/page.tsx
components/ui/button.tsx
lib/utils.ts
package-lock.json
package.json

footer 추가했습니다
pathname에 따라 footer와 header의 색이 변경됩니다.
각각 comit의 깃허브 인스타 카카오톡챗봇으로 연결됩니다
Close #6

feat(fe): add footer

---

app/(main)/_components/Header.tsx
app/(main)/layout.tsx
app/(main)/page.tsx

- Formatting
- TODO for Header component added
- None
- Future work: More TODOs

feat: code review & formatting

---

README.md

README 파일 생성 완료했습니다.
부족한 내용이 있다면 코멘트 부탁드리겠습니다
Closes #12

docs(fe): create README

---

app/(main)/study/page.tsx
components/common/Header.tsx
components/study/StudyCard.tsx
components/ui/badge.tsx
components/ui/card.tsx
package-lock.json
tailwind.config.ts

스터디 카드 추가했습니다.
16번 이슈는 스터디 dialog까지 추가 후 마무리하겠습니다.

feat(fe): add study card

---

app/(main)/(dark)/layout.tsx
app/(main)/(dark)/page.tsx
components/common/Header.tsx

모바일 버전일 때 햄버거가 안 보이는 에러가 있어 급하게 고쳤습니다.
메인 페이지의 반응형은 논의 후 고쳐야 될 거 같습니다.

hotfix: fix layout bug

---

app/(main)/(dark)/login/page.tsx
app/(main)/(dark)/signup/page.tsx
app/(main)/(light)/about/page.tsx
components/common/Header.tsx

layout 3차 수정입니다. about, login, signup 페이지 수정했으며
추가로 drawer 색상도 변경했습니다

hotfix: fix about auth layout, change drawer responsive to pathname

---

app/(main)/(dark)/page.tsx
app/(main)/(light)/about/page.tsx
app/(main)/(light)/study/open/page.tsx
app/(main)/(light)/study/page.tsx
components/about/IntroduceMemberCard.tsx
components/about/SectionCard.tsx
components/clubroom/ClubroomInfoCard.tsx
components/common/SectionBanner.tsx
components/main/StudyCard.tsx
components/study/StudyCard.tsx
components/ui/alert-dialog.tsx
components/ui/badge.tsx
package-lock.json
package.json

스터디 카드가 모바일에서 2줄로 보이게끔 수정하고
전체적인 반응형 css를 수정했습니다
Closes #39

feat(fe) edit study card, change media query css

---

app/(main)/(dark)/signup/page.tsx
app/(main)/(light)/study/open/page.tsx
app/(main)/(light)/study/page.tsx
components/ui/popover.tsx
package-lock.json
package.json

1. 스터디 개설 버튼 위치 변경
2. signup에 학번 필드 추가
3. 스택 도움말 버튼 추가
Closes #46 
dialog에서 자동으로 x 버튼에 focus 가는 것은
hidden input에 autofocus 주는 것으로 시도했으나 실패함

feat(fe): apply ksj comments

---

.eslintrc.json
.husky/pre-commit
app/admin/page.tsx
components/columns/Study.tsx
components/common/DataTable.tsx
components/common/Header.tsx
components/ui/table.tsx
lib/dummy.ts
package-lock.json
package.json

admin에서 공통으로 사용할 datatable을 만들고
reviewing opened closed table에서 공통적으로 사용할 Columns를 만들었습니다.
Closes #52

feat(fe): add admin study data table

---

app/admin/layout.tsx
app/admin/studies/closed/page.tsx
app/admin/studies/opened/page.tsx
app/admin/studies/reviewing/page.tsx
components/admin/Dropdown.tsx
components/admin/Header.tsx
components/admin/SideBar.tsx
components/columns/Study.tsx
components/ui/dropdown-menu.tsx

Data Table을 이용하여 study 페이지들 구현했습니다
각각
/admin/studies/reviewing
/admin/studies/opened
/admin/studies/closed
로 접속하면 확인할 수 있습니다
Closes #56

feat(fe) add admin study page

---

app/(main)/(light)/clubroom/page.tsx
components/clubroom/ClubroomCarousel.tsx

Clubroom Carousel 디자인 변경
1. 현재 Image를 숫자로 표시
2. Autoplay 추가
Closes #57

feat(fe): edit clubroom carousel design

---

app/(main)/(dark)/page.tsx

In this PR,
add arrow to main page for notice user scrolling

feat: add arrow to main page

---

app/(main)/(dark)/page.tsx

메인 페이지 반응형 디자인 수정했습니다
반드시 테스트 부탁드리겠습니다
Closes #63

style(fe): fix main page responsive style

---

app/(main)/(dark)/page.tsx
components/study/StudyCard.tsx
lib/dummy.ts

모집중 배지를 추가하였으며 isRecruiting이 true 일 때 배지를 보여줍니다.
study 분반 2개 추가했습니다
Closes #72

feat: add badge to study card

---

app/(main)/(light)/study/page.tsx
components/study/StudyCard.tsx
lib/dummy.ts

1. study detail modal의 줄바꿈을 단어 기준으로 수정
2. aws 스터디 더미 데이터 추가
3. 모집 마감 배지 추가
Closes #74 
Closes #75

hotfix: fix study detail new line, add aws study

---

app/(main)/(dark)/page.tsx
app/(main)/(light)/study/open/page.tsx
components/about/MemberList.tsx
components/common/Header/NavLink.tsx
components/common/Header/index.tsx
components/common/ScrollToTopButton.tsx
components/study/StudyList.tsx
constants/apiEndpoint.ts
constants/routes.ts
lib/fetch.ts

`NavLink`만 client component로 전환하고
`const pathname = usePathname()`에 따라 텍스트 색을 변경합니다.
Closes #92 
#93 을 해결하려고 시도했지만 `layout.tsx`의 구성으로 인해 스크롤을 내려도 `window, document`, `document.body`, `main` 등 주요 요소들의 스크롤 값이 0으로 고정됩니다.
아마 이런 구성을 사용한 이유는 `components/main/Main.tsx`의 다양한 애니메이션을 구현하기 위함으로 추측됩니다.(@B0XERCAT)
따라서 애니메이션 구현 방식과 스크롤바 숨김 처리 방식에 대한 논의가 필요합니다.

92 change navbar text color according to url

---

app/(main)/(dark)/page.tsx
components/about/MemberList.tsx
components/study/StudyList.tsx
constants/apiEndpoint.ts
package-lock.json

서버 측을 먼저 빌드하기 위한 임시 PR 입니다.
이후 클라이언트 측을 Push 하겠습니다.

Fix: merging issue

---

constants/apiEndpoint.ts

#104 merge 도중 발생한 이슈를 해결했습니다.
1. API Response 구조 변경
2. 빌드 시 기존 API에서 데이터를 불러옴
3. Response 구조 변경으로 인해 빌드 에러 발생
1. API 소비하는 모든 컴포넌트에서 소비 로직 주석 처리
2. API 서버 먼저 빌드
3. 이후 API를 소비하는 컴포넌트 주석 해제
4. 빌드 성공
원래 NextJS 풀스택 배포할 때 API를 소비하는 클라이언트 코드가 있으면 빌드가 안된다는 것은 말이 안된다고 생각합니다.
분명 제가 작성한 코드에 문제가 있는 것 같은데 이에 대해 아시는 분 있으면 알려주시면 감사하겠습니다.
제가 NextJS로 풀스택을 작성하는 것은 처음이라 빌드 순서 상의 에러가 발생했던 것으로 보입니다.
그동안 PR 밀렸을 건데 죄송합니다!
@Imjungjuna @jihostudy 
Resolve #104

hotfix: set baseURL as localhost

---

app/(main)/(dark)/page.tsx
components/about/MemberList.tsx
components/study/StudyList.tsx
constants/apiEndpoint.ts

#110 에서 API 소비하는 컴포넌트 주석 해제가 되지 않았습니다...

hotfix: uncomment API consuming codes

---

collections/Admin.postman_collection.json
collections/Client.postman_collection.json

포스트맨 collection json 파일을 추가했습니다.
백엔드팀의 경우 팀 워크스페이스로 공유할 예정이고
죄송하지만 프론트 팀은 저희가 변경사항을 업데이트하면
json 파일을 import 해서 사용해주시면 감사드리겠습니다.
PR이 머지 되면 git pull 한 뒤, 
Admin.postman_collection.json, Client.postman_collection.json 
2개의 파일을 다운 받아주세요!
회원가입 / 로그인 해주세요~ 
Import 버튼을 눌러 collection들을 import 해주세요!
Closes #127

feat: add auth collection.json

---

app/(main)/study/[id]/signup/page.tsx
app/(main)/study/open/page.tsx
app/(main)/study/page.tsx
components/clubroom/ClubroomMainContent.tsx

스터디 개설, 스터디 신청, 스터디 페이지 등의 레이아웃을 수정했고
스터디 페이지의 이미지 섹션을 삭제했습니다.
추가로 동방 페이지 하단에 마진 추가했습니다
Closes #144

fix: fix open study bug

---

_middleware.ts
app/(main)/login/page.tsx
app/(main)/study/[id]/signup/page.tsx
app/(main)/study/open/page.tsx
app/admin/page.tsx
app/admin/studies/page.tsx
app/admin/users/page.tsx
app/api/studies/[id]/signup/route.ts
components/about/IntroduceMemberCard.tsx
components/about/MemberList.tsx
components/admin/DataTable/EditableCell.tsx
components/admin/DataTable/columns/Study.tsx
components/admin/DataTable/columns/User.tsx
components/common/StudyCard/index.tsx
components/common/User/HoverCard.tsx
components/main/ExampleStudyList.tsx
components/study/StudyList.tsx
components/study/signup/StudySignupForm.tsx
constants/apiEndpoint.ts
lib/auth/auth.ts
lib/supabase/client.ts
middleware.ts
package-lock.json
package.json
types/auth.d.ts
types/index.ts

- 리다이렉트 안되는 버그
- Study.stacks null 인 경우 처리
Close #134

134 connect backend

---

app/(main)/layout.tsx
app/(main)/study/open/page.tsx
components/admin/DataTable/EditableCell.tsx
components/admin/DataTable/columns/Study.tsx
components/common/Header/index.tsx
components/ui/toast.tsx
components/ui/toaster.tsx
components/ui/use-toast.ts
package-lock.json
package.json

164 add study open page fetch data

---

components/admin/DataTable/columns/User.tsx
constants/apiEndpoint.ts

Admin User DataTable에서 position을 fetch할 수 있게 
api endpoint를 추가하고 api 연결했습니다
Closes #176

feat(fe): add patch position in user data table

---

components/common/Header/Profile.tsx
components/main/ExampleStudyList.tsx
constants/routes.ts
lib/auth/AuthProvider.tsx
lib/auth/auth.ts
lib/auth/callbackFunctions/parameters.ts
types/auth.d.ts

- 백엔드 서버에서 보내주는 `role` 필드를 기준으로 접근 권한을 설정합니다.
- Navbar Profile의 관리자 바로가기 표시 여부, 어드민 페이지 접근이 해당됩니다.
Close #159 
Close #172 
- 누락된 header와 body 정보를 추가했습니다.
Close #164

Fix minor UI bugs

---

app/(main)/mystudy/page.tsx
app/(main)/profile/_components/ProfileCards.tsx
app/(main)/profile/page.tsx
components/admin/DataTable/ControlHeader.tsx
constants/apiEndpoint.ts
constants/zodSchema/profileUpdate.ts
lib/supabase/hooks.ts

MY Profile 페이지 구현했습니다!
Closes #166

feat(fe): implement profile page

---

app/(main)/mystudy/layout.tsx
app/(main)/mystudy/mystudy.css
app/(main)/signup/page.tsx
app/(main)/signup/signup.css
components/common/Header/NavLink.tsx
components/common/Header/Profile.tsx
components/common/Header/index.tsx

pretendard 전체 적용을 위해서는 대대적인 프로젝트 구조 개선이 필요할 것 같습니다.
일단은 부분적으로 pretendard 적용된 부분을 삭제하고
Nav 쪽의 한글 텍스트들의 폰트를 굵게 했습니다

fix: delete pretendard, change korean text font bolder

---

app/(main)/login/page.tsx
app/(main)/signup/page.tsx
app/(main)/study/open/page.tsx
components/ui/tabs.tsx
package-lock.json
package.json

Login이랑 Study create 할 때 isSubmitting 이용해서 연타 방지
스터디 개설에서 라디오 -> Shadcn Tabs로 변경
Closes #188

fix: disable button right after fetch

---

app/(main)/mystudy/[id]/page.tsx
app/(main)/mystudy/page.tsx
constants/apiEndpoint.ts
lib/supabase/hooks.ts

배포/개발 환경에 따라 업로드 되는 디렉터리를 나눴습니다.
스터디 업데이트 API를 연결했습니다.

170 connect mypage with backend

---

next.config.js

chore: set next CORS headers
